<?php
if (($shieldgroup_slider_sc = shieldgroup_get_theme_option('front_page_title_shortcode')) != '' && strpos($shieldgroup_slider_sc, '[')!==false && strpos($shieldgroup_slider_sc, ']')!==false) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider"><?php
		// Add anchor
		$shieldgroup_anchor_icon = shieldgroup_get_theme_option('front_page_title_anchor_icon');	
		$shieldgroup_anchor_text = shieldgroup_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($shieldgroup_anchor_icon) || !empty($shieldgroup_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($shieldgroup_anchor_icon) ? ' icon="'.esc_attr($shieldgroup_anchor_icon).'"' : '')
											. (!empty($shieldgroup_anchor_text) ? ' title="'.esc_attr($shieldgroup_anchor_text).'"' : '')
											. ']');
		}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode($shieldgroup_slider_sc);
	?></div><?php

} else {

	?><div class="front_page_section front_page_section_title<?php
				$shieldgroup_scheme = shieldgroup_get_theme_option('front_page_title_scheme');
				if (!shieldgroup_is_inherit($shieldgroup_scheme)) echo ' scheme_'.esc_attr($shieldgroup_scheme);
				echo ' front_page_section_paddings_'.esc_attr(shieldgroup_get_theme_option('front_page_title_paddings'));
			?>"<?php
			$shieldgroup_css = '';
			$shieldgroup_bg_image = shieldgroup_get_theme_option('front_page_title_bg_image');
			if (!empty($shieldgroup_bg_image)) 
				$shieldgroup_css .= 'background-image: url('.esc_url(shieldgroup_get_attachment_url($shieldgroup_bg_image)).');';
			if (!empty($shieldgroup_css))
				echo ' style="' . esc_attr($shieldgroup_css) . '"';
	?>><?php
		// Add anchor
		$shieldgroup_anchor_icon = shieldgroup_get_theme_option('front_page_title_anchor_icon');	
		$shieldgroup_anchor_text = shieldgroup_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($shieldgroup_anchor_icon) || !empty($shieldgroup_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($shieldgroup_anchor_icon) ? ' icon="'.esc_attr($shieldgroup_anchor_icon).'"' : '')
											. (!empty($shieldgroup_anchor_text) ? ' title="'.esc_attr($shieldgroup_anchor_text).'"' : '')
											. ']');
		}
		?>
		<div class="front_page_section_inner front_page_section_title_inner<?php
			if (shieldgroup_get_theme_option('front_page_title_fullheight'))
				echo ' shieldgroup-full-height sc_layouts_flex sc_layouts_columns_middle';
			?>"<?php
				$shieldgroup_css = '';
				$shieldgroup_bg_mask = shieldgroup_get_theme_option('front_page_title_bg_mask');
				$shieldgroup_bg_color = shieldgroup_get_theme_option('front_page_title_bg_color');
				if (!empty($shieldgroup_bg_color) && $shieldgroup_bg_mask > 0)
					$shieldgroup_css .= 'background-color: '.esc_attr($shieldgroup_bg_mask==1
																		? $shieldgroup_bg_color
																		: shieldgroup_hex2rgba($shieldgroup_bg_color, $shieldgroup_bg_mask)
																	).';';
				if (!empty($shieldgroup_css))
					echo ' style="' . esc_attr($shieldgroup_css) . '"';
		?>>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$shieldgroup_caption = shieldgroup_get_theme_option('front_page_title_caption');
				if (!empty($shieldgroup_caption) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo !empty($shieldgroup_caption) ? 'filled' : 'empty'; ?>"><?php echo wp_kses_post($shieldgroup_caption); ?></h1><?php
				}
			
				// Description (text)
				$shieldgroup_description = shieldgroup_get_theme_option('front_page_title_description');
				if (!empty($shieldgroup_description) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo !empty($shieldgroup_description) ? 'filled' : 'empty'; ?>"><?php echo wp_kses_post(wpautop($shieldgroup_description)); ?></div><?php
				}
				
				// Buttons
				if (shieldgroup_get_theme_option('front_page_title_button1_link')!='' || shieldgroup_get_theme_option('front_page_title_button2_link')!='') {
					?><div class="front_page_section_buttons front_page_section_title_buttons"><?php
						shieldgroup_show_layout(shieldgroup_customizer_partial_refresh_front_page_title_button1_link());
						shieldgroup_show_layout(shieldgroup_customizer_partial_refresh_front_page_title_button2_link());
					?></div><?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}